apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cstor-disk-pool
  namespace: openebs
spec:
  pools:
    - nodeSelector:
        kubernetes.io/hostname: "ecpaas-master"
      dataRaidGroups:
        - blockDevices:
          - blockDeviceName: "blockdevice-85afb5acfc3d813d3b021fa9d606daea"
      poolConfig:
        dataRaidGroupType: "stripe"
    - nodeSelector:
          kubernetes.io/hostname: "ecpaas-worker1"
      dataRaidGroups:
        - blockDevices:
          - blockDeviceName: "blockdevice-4b0c23470f77709b2bcb9a1a876f01ac"
      poolConfig:
        dataRaidGroupType: "stripe"


