
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: ecpaas-master, address: 192.168.40.8, internalAddress: 192.168.200.254, user: manager, password: "nova"}
  - {name: ecpaas-worker1, address: 192.168.40.9, internalAddress: 192.168.200.1, user: manager, password: "nova"}
  roleGroups:
    etcd:
    - ecpaas-master
    control-plane: 
    - ecpaas-master
    worker:
    - ecpaas-master
    - ecpaas-worker1
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.32.4
    clusterName: ecpass.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: none
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: true
  registry:
    privateRegistry: "ecpaas-dockerhub.atan-networks.com.cn"
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: 
  - name: calico
    namespace: kube-system
    sources:
       yaml:
         path:
           - https://raw.githubusercontent.com/projectcalico/calico/release-v3.29/manifests/calico.yaml

  - name: openelb
    namespace: openelb-system
    sources:
       yaml:
         path: 
           - https://raw.githubusercontent.com/openelb/openelb/release-0.6/deploy/openelb.yaml
